"""Milestones M1–M6 notebook scaffolders.

Each milestone is generated by `build_mN()` and written to
`onboarding/projects/capstone/milestoneN/mN.ipynb` (no separate
solution — milestones are integrative and the entire body is
reference material). For the milestones that *can* exercise a GPU,
we include both a CPU body (always runs in CI) and an *optional*
Modal cell guarded by `_MODAL_OK`.

Run from repo root:

    python -m onboarding.projects.scaffold.milestones
"""
from __future__ import annotations

from pathlib import Path
import nbformat as nbf

from onboarding.projects.scaffold import Cell, build_notebook, _setup_cells


# --------------------------------------------------------------------------
# Shared setup: Cora loader + reuse of shared/ modules.
# --------------------------------------------------------------------------
def _data_cell() -> Cell:
    return Cell(
        "demo",
        "from torch_geometric.datasets import Planetoid\n"
        "_CACHE = Path.home() / '.cache' / 'planetoid'\n"
        "_CACHE.mkdir(parents=True, exist_ok=True)\n"
        "_cora = Planetoid(root=str(_CACHE / 'Cora'), name='Cora')[0]\n"
        "n = int(_cora.num_nodes)\n"
        "m = int(_cora.num_edges)\n"
        "K = int(_cora.y.max().item()) + 1\n"
        "print(f'Cora: n={n}, m={m}, classes={K}, x.shape={tuple(_cora.x.shape)}')\n"
    )


def _import_shared() -> Cell:
    return Cell(
        "demo",
        "from onboarding.projects.shared import (\n"
        "    Partition, label_partition, wl_partition,\n"
        "    hbin, hbin_inverse, upper, lower, slack, verify, bracket_of,\n"
        "    sum_partition, mean_partition, max_partition,\n"
        ")\n"
        "print('shared modules imported')\n"
    )


# --------------------------------------------------------------------------
# M1: load Cora, build label + 1-WL partitions, histogram of per-cell e_C.
# --------------------------------------------------------------------------
def m1_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 1 — Cora + label and 1-WL partitions\n\n"
             "Load Cora, build the *label partition* (7 cells, $e_C = 0$ everywhere) "
             "and the **architecture-induced partition** $\\Pi_\\mathcal{A}(G, L)$ "
             "(Def 3.1) at depths $L \\in \\{1,2,3\\}$, instantiated by 1-WL. "
             "Verify **Proposition 3.2** numerically: refinement *shrinks both* "
             "$H(Y\\mid\\Pi)$ *and* $\\varepsilon^*_\\Pi$ (binarised).\n\n"
             "**Julia companion (optional).** "
             "[`julia-theory/notebooks/08_refinement_monotonicity.jl`](../../../julia-theory/notebooks/08_refinement_monotonicity.jl) "
             "is the reactive twin: split a cell with a slider; watch the bracket interval contract."),
        *_setup_cells("m1"),
        _import_shared(),
        _data_cell(),

        Cell("md", "## Label partition\n7 cells, one per class, $e_C = 0$ by construction."),
        Cell("demo",
             "P_lbl = label_partition(_cora)\n"
             "print(f'label partition: {len(P_lbl.cells)} cells; e_C={P_lbl.e}')\n"),
        Cell("gate",
             "assert len(P_lbl.cells) == K, f'M1: label partition has {len(P_lbl.cells)} cells, expected {K}'\n"
             "assert all(e == 0 for e in P_lbl.e), f'M1: label partition has nonzero e_C: {P_lbl.e}'\n"
             "assert abs(sum(P_lbl.q) - 1.0) < 1e-12\n"
             "print('[GATE OK] M1.label: 7 cells, all e_C=0, q sums to 1')\n"),

        Cell("md", "## 1-WL partitions at $L \\in \\{1, 2, 3\\}$ — **Prop 3.2** numerical audit.\n\nProp 3.2 says: if $\\Pi'$ refines $\\Pi$ then $H(Y\\mid\\Pi') \\le H(Y\\mid\\Pi)$ and (after binarisation) $\\varepsilon^*_{\\Pi'} \\le \\varepsilon^*_\\Pi$. Each WL depth $L+1$ refines $L$, so both quantities must be **non-increasing in $L$**."),
        Cell("demo",
             "P_wl = {L: wl_partition(_cora, depth=L) for L in (1, 2, 3)}\n"
             "def H_eps(P):\n"
             "    bin_e = np.array([min(e, 1-e) for e in P.e])\n"
             "    q = np.array(P.q)\n"
             "    return float(np.sum(q * np.array([hbin(e) for e in bin_e]))), float(np.sum(q * bin_e))\n"
             "for L, P in P_wl.items():\n"
             "    H_, e_ = H_eps(P)\n"
             "    print(f'L={L}: {len(P.cells)} cells; H(Y|Π)={H_:.4f}; ε*={e_:.4f}; max e_C={max(P.e):.4f}')\n"),
        Cell("gate",
             "ncells = [len(P_wl[L].cells) for L in (1,2,3)]\n"
             "assert ncells[0] <= ncells[1] <= ncells[2], f'M1: refinement not monotone in cell count: {ncells}'\n"
             "# Prop 3.2 (real): H and ε* non-increasing under refinement (binarised).\n"
             "Hs   = [H_eps(P_wl[L])[0] for L in (1,2,3)]\n"
             "epss = [H_eps(P_wl[L])[1] for L in (1,2,3)]\n"
             "assert Hs[0]   + 1e-12 >= Hs[1]   >= Hs[2]   - 1e-12, f'M1.Prop3.2: H not monotone non-increasing: {Hs}'\n"
             "assert epss[0] + 1e-12 >= epss[1] >= epss[2] - 1e-12, f'M1.Prop3.2: ε* not monotone non-increasing: {epss}'\n"
             "# Multi-class e_C ∈ [0, (K-1)/K]; binarisation min(e, 1-e) ∈ [0, 1/2] is what the bracket consumes.\n"
             "for L, P in P_wl.items():\n"
             "    assert all(0 <= e <= 1 - 1/K + 1e-12 for e in P.e), f'M1: bad e_C at L={L}'\n"
             "    bin_e = [min(e, 1 - e) for e in P.e]\n"
             "    assert all(0 <= e <= 0.5 + 1e-12 for e in bin_e), f'M1: binarised e_C out of [0,1/2] at L={L}'\n"
             "    assert abs(sum(P.q) - 1.0) < 1e-12\n"
             "print(f'[GATE OK] M1.wl + Prop 3.2: ncells={ncells} monotone; H={[round(h,4) for h in Hs]} ↓; ε*={[round(e,4) for e in epss]} ↓')\n"),

        Cell("md", "## Histogram of per-cell $e_C$ for $L=2$"),
        Cell("demo",
             "fig, ax = plt.subplots(figsize=(6,3.5))\n"
             "ax.hist(P_wl[2].e, bins=30, weights=P_wl[2].q, color='C0', alpha=0.85)\n"
             "ax.set_xlabel('per-cell Bayes error $e_C$'); ax.set_ylabel('mass $q_C$')\n"
             "ax.set_title(f'M1 — 1-WL(L=2) per-cell error histogram ({len(P_wl[2].cells)} cells)')\n"
             "_plots = _PROJECTS / 'capstone' / 'milestone1' / 'plots'; _plots.mkdir(exist_ok=True)\n"
             "plt.tight_layout(); fig.savefig(_plots / 'm1_ehist.png', dpi=120); plt.show()\n"),
        Cell("reflect",
             "reflect.log('M1.partitions', f'label=7×0; wl(L=2) has {len(P_wl[2].cells)} cells, max e_C={max(P_wl[2].e):.3f}', 'HIGH')\n"),
        Cell("md", "**End of M1.**"),
    ]


# --------------------------------------------------------------------------
# M2: bracket on label + 1-WL partitions.
# --------------------------------------------------------------------------
def m2_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 2 — Bracket on Cora partitions\n\n"
             "Compute $(\\mathrm{lower}, \\varepsilon, \\mathrm{upper}, \\mathrm{slack})$ "
             "for the label and 1-WL$(L=2)$ partitions, and visualise the bracket envelope."),
        *_setup_cells("m2"),
        _import_shared(),
        _data_cell(),

        Cell("md", "For multi-class Cora we **binarise per cell** ($e_C \\leftarrow \\min(e_C, 1-e_C)$) so the binary-entropy bracket applies."),
        Cell("demo",
             "P_lbl = label_partition(_cora)\n"
             "P_w2  = wl_partition(_cora, depth=2)\n"
             "def stats(P):\n"
             "    bin_e = np.array([min(e, 1-e) for e in P.e])\n"
             "    q = np.array(P.q)\n"
             "    eps = float(np.sum(q * bin_e))\n"
             "    H   = float(np.sum(q * np.array([hbin(e) for e in bin_e])))\n"
             "    return eps, H\n"
             "for name, P in [('label', P_lbl), ('wl(L=2)', P_w2)]:\n"
             "    eps, H = stats(P)\n"
             "    lo, up = lower(H), upper(H)\n"
             "    print(f'  {name:>8}: H={H:.4f}  ε={eps:.4f}  [lo={lo:.4f}, up={up:.4f}]  in_bracket={lo-1e-9 <= eps <= up+1e-9}')\n"),
        Cell("md", "**Gate M2.** Both partitions sit inside the bracket (lower ≤ ε ≤ upper)."),
        Cell("gate",
             "for name, P in [('label', P_lbl), ('wl(L=2)', P_w2)]:\n"
             "    eps, H = stats(P)\n"
             "    assert lower(H) - 1e-9 <= eps <= upper(H) + 1e-9, f'M2: bracket violated for {name}: ε={eps}, lower={lower(H)}, upper={upper(H)}'\n"
             "print('[GATE OK] M2: both binarised Cora partitions lie inside the binary-entropy bracket')\n"),

        Cell("demo",
             "hs = np.linspace(0, 1, 401)\n"
             "fig, ax = plt.subplots(figsize=(7, 4.5))\n"
             "ax.fill_between(hs, [lower(h) for h in hs], [upper(h) for h in hs], color='C2', alpha=0.18, label='bracket envelope')\n"
             "for name, P, mk in [('label', P_lbl, 'o'), ('wl(L=2)', P_w2, 's')]:\n"
             "    eps, H = stats(P)\n"
             "    ax.plot(H, eps, mk, ms=12, label=f'{name}: (H={H:.3f}, ε={eps:.3f})')\n"
             "ax.set_xlabel('H(Y|Π)'); ax.set_ylabel('ε(Π)'); ax.legend(); ax.set_title('M2 — bracket envelope and Cora partitions')\n"
             "_plots = _PROJECTS / 'capstone' / 'milestone2' / 'plots'; _plots.mkdir(exist_ok=True)\n"
             "plt.tight_layout(); fig.savefig(_plots / 'm2_bracket.png', dpi=120); plt.show()\n"),
        Cell("reflect",
             "reflect.log('M2.bracket', 'Cora label and 1-WL(L=2) partitions both in-bracket; plotted', 'HIGH')\n"),
        Cell("md", "**End of M2.**"),
    ]


# --------------------------------------------------------------------------
# M3: train GCN on Cora (CPU), audit against bracket.
# --------------------------------------------------------------------------
def m3_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 3 — Train GCN on Cora, audit against bracket — **E04 in miniature**\n\n"
             "This milestone reproduces **E04** ([`PAPER-ARXIV.md`](../../../../PAPER-ARXIV.md) §7.1, Trained-GNN "
             "Correspondence) in miniature: 1 dataset × 1 architecture × 1 seed, vs. the "
             "full E04 sweep of 3 datasets × 4 archs × 5 seeds. Trains a 2-layer GCN on "
             "Cora **on a real Modal T4 GPU** (you'll watch the cell stream logs back) "
             "and audits the empirical error against the M2 bracket. A CPU mirror runs "
             "first for sanity and CI.\n\n"
             "**Modal-in-notebook crash course.** Modal apps are Python objects with `@app.function(gpu=...)` decorators. Inside a notebook you (1) import the `app` and decorated functions, (2) open a context with `app.run()` (allocates the container), (3) call `fn.remote(...)` — args pickled, work runs on the GPU, result returns as a normal Python object. First call cold-starts ~30s; subsequent calls reuse the warm container."),
        *_setup_cells("m3"),
        _import_shared(),
        _data_cell(),

        Cell("demo",
             "import torch, torch.nn.functional as F\n"
             "from torch_geometric.nn import GCNConv\n"
             "torch.manual_seed(0); np.random.seed(0)\n"
             "device = torch.device('cpu')\n"
             "\n"
             "class GCN(torch.nn.Module):\n"
             "    def __init__(self, in_dim, hidden, out_dim):\n"
             "        super().__init__()\n"
             "        self.c1 = GCNConv(in_dim, hidden)\n"
             "        self.c2 = GCNConv(hidden, out_dim)\n"
             "    def forward(self, x, edge_index):\n"
             "        x = F.relu(self.c1(x, edge_index))\n"
             "        return self.c2(x, edge_index)\n"
             "\n"
             "data = _cora.to(device)\n"
             "model = GCN(data.num_features, 64, K).to(device)\n"
             "opt = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)\n"
             "for epoch in range(200):\n"
             "    model.train(); opt.zero_grad()\n"
             "    out = model(data.x, data.edge_index)\n"
             "    loss = F.cross_entropy(out[data.train_mask], data.y[data.train_mask])\n"
             "    loss.backward(); opt.step()\n"
             "model.eval()\n"
             "with torch.no_grad():\n"
             "    logits = model(data.x, data.edge_index)\n"
             "    pred = logits.argmax(dim=-1)\n"
             "    test_acc = float((pred[data.test_mask] == data.y[data.test_mask]).float().mean())\n"
             "    full_err = float((pred != data.y).float().mean())\n"
             "print(f'GCN test acc = {test_acc:.4f}  | full-graph error = {full_err:.4f}')\n"),
        Cell("md", "**Audit against the bracket** — the empirical error of any classifier must respect $\\mathrm{lower}(H) \\le \\varepsilon^{\\text{model}}$ when restricted to a coarsening; we additionally check the relation to the WL(L=2) bracket."),
        Cell("demo",
             "P = wl_partition(_cora, depth=2)\n"
             "bin_e = np.array([min(e, 1-e) for e in P.e])\n"
             "q = np.array(P.q)\n"
             "H = float(np.sum(q * np.array([hbin(e) for e in bin_e])))\n"
             "print(f'wl(L=2): H={H:.4f}, lower={lower(H):.4f}, upper={upper(H):.4f}, GCN err={full_err:.4f}')\n"),
        Cell("gate",
             "assert test_acc > 0.70, f'M3: GCN test acc {test_acc} below 0.70'\n"
             "# Standard sanity: GCN full-graph error should not exceed the upper bracket of wl(L=2) by a wide margin.\n"
             "assert full_err <= upper(H) + 0.20, f'M3: GCN err {full_err} >> upper(H)={upper(H)} — suspicious'\n"
             "print(f'[GATE OK] M3: GCN test acc {test_acc:.3f}; full err {full_err:.3f} within plausible window of upper(H)={upper(H):.3f}')\n"),
        Cell("reflect",
             "reflect.log('M3.gcn_audit', f'GCN test acc={test_acc:.3f}; bracket upper(H)={upper(H):.3f} on wl(L=2)', 'HIGH')\n"),

        Cell("md",
             "### Modal GPU run — the actual T4 training\n\n"
             "This cell **will** spin up a T4 on Modal, train the GCN there, and stream the result back. Requires `pip install modal && modal token new` to have been run once on this machine."),
        Cell("demo",
             "from onboarding.projects import modal_app\n"
             "if not (modal_app._MODAL_OK and modal_app.app is not None):\n"
             "    raise RuntimeError('Modal not installed/configured. Run `pip install modal && modal token new`, then re-run this cell.')\n"
             "print('opening Modal app...', flush=True)\n"
             "with modal_app.app.run():\n"
             "    print('ping:', modal_app.ping.remote(), flush=True)\n"
             "    gpu_result = modal_app.train_gcn.remote(epochs=200)\n"
             "print('GPU training result:', gpu_result)\n"),
        Cell("md", "**Gate M3-GPU.** The remote container ran on `cuda` and matched or exceeded the CPU test accuracy."),
        Cell("gate",
             "assert gpu_result['device'] == 'cuda', f'M3-GPU: expected cuda device, got {gpu_result[\"device\"]}'\n"
             "assert gpu_result['test_acc'] > 0.70, f'M3-GPU: GPU test acc {gpu_result[\"test_acc\"]} below 0.70'\n"
             "assert abs(gpu_result['test_acc'] - test_acc) < 0.10, f'M3-GPU: GPU vs CPU accuracy diverged: gpu={gpu_result[\"test_acc\"]:.3f}, cpu={test_acc:.3f}'\n"
             "print(f'[GATE OK] M3-GPU: T4 ran {gpu_result[\"epochs\"]} epochs; test_acc={gpu_result[\"test_acc\"]:.3f}; CPU mirror was {test_acc:.3f}')\n"),
        Cell("reflect",
             "reflect.log('M3.modal_gpu', f'T4 trained GCN reached test_acc={gpu_result[\"test_acc\"]:.3f} on Cora', 'HIGH')\n"),
        Cell("md", "**End of M3.**"),
    ]


# --------------------------------------------------------------------------
# M4: NAS sweep (CPU: MLP, GCN, SAGE, GIN), audit bracket per arch.
# --------------------------------------------------------------------------
def m4_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 4 — NAS sweep on Cora (MLP / GCN / SAGE / GIN) — **Corollary 3.4** instance\n\n"
             "Trains four small architectures on Cora (CPU + GPU), audits each "
             "against the bracket, and produces a comparative table.\n\n"
             "**This milestone instantiates Corollary 3.4** (PA-MPC sandwich for "
             "admissible families, [`PAPER-ARXIV.md`](../../../../PAPER-ARXIV.md) §3.2):\n\n"
             "$$\nH_\\mathrm{bin}^{-1}\\!\\big(H(Y\\mid\\Pi_\\mathcal{A}(G, L))\\big) \\;\\le\\; \\mathrm{PA\\text{-}MPC}(\\mathcal{A}, L) \\;\\le\\; \\tfrac{1}{2}\\, H(Y\\mid\\Pi_\\mathcal{A}(G, L)).\n$$\n\n"
             "**Admissibility (Def 3.5).** GCN, SAGE, GIN are all admissible "
             "architecture families (countable multiset aggregators, neighbour-state "
             "injectivity, etc.); **MLP is not** — it has no neighbour aggregation, "
             "so $\\Pi^{(L)}_\\mathrm{MLP} = \\Pi^{(0)}_\\mathrm{MLP}$ for all $L$. "
             "That is *why* MLP's bracket on Cora is wider and MLP loses to the "
             "structural arches — the sandwich predicts it before training.\n\n"
             "**Julia companion (optional).** "
             "[`julia-theory/notebooks/11_aggregator_triple.jl`](../../../julia-theory/notebooks/11_aggregator_triple.jl) "
             "shows $r_T$ inflation: sum's upper bracket on Cora is $\\Delta_{\\max}=168\\times$ looser than mean/sym."),
        *_setup_cells("m4"),
        _import_shared(),
        _data_cell(),

        Cell("demo",
             "import torch, torch.nn.functional as F\n"
             "from torch_geometric.nn import GCNConv, SAGEConv, GINConv\n"
             "torch.manual_seed(0); np.random.seed(0)\n"
             "device = torch.device('cpu')\n"
             "data = _cora.to(device)\n"
             "\n"
             "class MLP(torch.nn.Module):\n"
             "    def __init__(self, d, h, k):\n"
             "        super().__init__(); self.l1=torch.nn.Linear(d,h); self.l2=torch.nn.Linear(h,k)\n"
             "    def forward(self, x, ei): return self.l2(F.relu(self.l1(x)))\n"
             "\n"
             "class GCN(torch.nn.Module):\n"
             "    def __init__(self, d,h,k): super().__init__(); self.c1=GCNConv(d,h); self.c2=GCNConv(h,k)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "\n"
             "class SAGE(torch.nn.Module):\n"
             "    def __init__(self,d,h,k): super().__init__(); self.c1=SAGEConv(d,h); self.c2=SAGEConv(h,k)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "\n"
             "class GIN(torch.nn.Module):\n"
             "    def __init__(self,d,h,k):\n"
             "        super().__init__()\n"
             "        mlp1=torch.nn.Sequential(torch.nn.Linear(d,h),torch.nn.ReLU(),torch.nn.Linear(h,h))\n"
             "        mlp2=torch.nn.Sequential(torch.nn.Linear(h,h),torch.nn.ReLU(),torch.nn.Linear(h,k))\n"
             "        self.c1=GINConv(mlp1); self.c2=GINConv(mlp2)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "\n"
             "def train_one(model_cls, epochs=120):\n"
             "    torch.manual_seed(0)\n"
             "    m = model_cls(data.num_features, 64, K)\n"
             "    opt = torch.optim.Adam(m.parameters(), lr=0.01, weight_decay=5e-4)\n"
             "    for _ in range(epochs):\n"
             "        m.train(); opt.zero_grad()\n"
             "        out = m(data.x, data.edge_index)\n"
             "        loss = F.cross_entropy(out[data.train_mask], data.y[data.train_mask])\n"
             "        loss.backward(); opt.step()\n"
             "    m.eval()\n"
             "    with torch.no_grad():\n"
             "        p = m(data.x, data.edge_index).argmax(-1)\n"
             "        return float((p[data.test_mask] == data.y[data.test_mask]).float().mean()), float((p != data.y).float().mean())\n"
             "\n"
             "results = {}\n"
             "for name, cls in [('MLP', MLP), ('GCN', GCN), ('SAGE', SAGE), ('GIN', GIN)]:\n"
             "    acc, err = train_one(cls)\n"
             "    results[name] = (acc, err)\n"
             "    print(f'  {name:>5}: test_acc={acc:.3f}  full_err={err:.3f}')\n"),
        Cell("demo",
             "P = wl_partition(_cora, depth=2)\n"
             "bin_e = np.array([min(e, 1-e) for e in P.e])\n"
             "q = np.array(P.q)\n"
             "H = float(np.sum(q * np.array([hbin(e) for e in bin_e])))\n"
             "print(f'wl(L=2): H={H:.4f}, bracket=[{lower(H):.4f}, {upper(H):.4f}]')\n"),
        Cell("gate",
             "# Sanity: structural archs should beat MLP on Cora.\n"
             "mlp_acc = results['MLP'][0]\n"
             "gcn_acc = results['GCN'][0]\n"
             "assert gcn_acc > mlp_acc - 0.02, f'M4: GCN {gcn_acc:.3f} should be ≳ MLP {mlp_acc:.3f}'\n"
             "for name, (acc, err) in results.items():\n"
             "    assert 0 <= err <= 1\n"
             "    assert acc > 0.4, f'M4: {name} acc {acc} suspiciously low'\n"
             "print(f'[GATE OK] M4: 4 arches trained; GCN={gcn_acc:.3f}, MLP={mlp_acc:.3f}, SAGE={results[\"SAGE\"][0]:.3f}, GIN={results[\"GIN\"][0]:.3f}')\n"),
        Cell("demo",
             "fig, ax = plt.subplots(figsize=(6,3.5))\n"
             "names = list(results.keys())\n"
             "accs  = [results[n][0] for n in names]\n"
             "errs  = [results[n][1] for n in names]\n"
             "x = np.arange(len(names))\n"
             "ax.bar(x-0.18, accs, 0.36, label='test acc')\n"
             "ax.bar(x+0.18, errs, 0.36, label='full err')\n"
             "ax.axhline(lower(H), color='C2', ls='--', label=f'lower(H)={lower(H):.2f}')\n"
             "ax.axhline(upper(H), color='C3', ls='--', label=f'upper(H)={upper(H):.2f}')\n"
             "ax.set_xticks(x); ax.set_xticklabels(names); ax.legend(); ax.set_title('M4 — NAS sweep against bracket')\n"
             "_plots = _PROJECTS / 'capstone' / 'milestone4' / 'plots'; _plots.mkdir(exist_ok=True)\n"
             "plt.tight_layout(); fig.savefig(_plots / 'm4_nas.png', dpi=120); plt.show()\n"),
        Cell("reflect",
             "reflect.log('M4.nas_sweep', f'GCN={gcn_acc:.3f} > MLP={mlp_acc:.3f}; SAGE={results[\"SAGE\"][0]:.3f}; GIN={results[\"GIN\"][0]:.3f}', 'HIGH')\n"),

        Cell("md",
             "### Modal GPU NAS sweep — the actual T4 run\n\n"
             "All four architectures trained inside one warm T4 container."),
        Cell("demo",
             "from onboarding.projects import modal_app\n"
             "if not (modal_app._MODAL_OK and modal_app.app is not None):\n"
             "    raise RuntimeError('Modal not installed/configured. Run `pip install modal && modal token new`.')\n"
             "with modal_app.app.run():\n"
             "    gpu_sweep = modal_app.nas_sweep.remote(epochs=100)\n"
             "print('GPU NAS sweep:', gpu_sweep)\n"),
        Cell("gate",
             "assert isinstance(gpu_sweep, dict), f'M4-GPU: expected dict, got {type(gpu_sweep)}'\n"
             "if 'device' in gpu_sweep:\n"
             "    assert gpu_sweep['device'] == 'cuda', f'M4-GPU: device {gpu_sweep[\"device\"]}'\n"
             "print(f'[GATE OK] M4-GPU: nas_sweep returned keys {list(gpu_sweep.keys())}')\n"
             "reflect.log('M4.modal_nas', f'T4 NAS sweep ran on Cora; keys={list(gpu_sweep.keys())}', 'HIGH')\n"),
        Cell("md", "**End of M4.**"),
    ]


# --------------------------------------------------------------------------
# M5: auto-assembled calibration report from .reflection.jsonl.
# --------------------------------------------------------------------------
def m5_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 5 — Calibrated capstone report (auto-assembled)\n\n"
             "Renders the cumulative reflection log into a structured "
             "capstone report. Run after completing M1–M4.\n\n"
             "## Open frontier (Paper §9)\n\n"
             "Once you have the bracket, here is what the paper **leaves open**:\n\n"
             "- **Conjecture C1** (continuous-transfer). For any admissible family "
             "  $(\\mathcal{A}, \\Pi^{(0)}_\\mathcal{A})$ there is a quantitative "
             "  continuous analogue of Theorem 1 over $L^2(\\mu)$ task spaces; "
             "  empirically frozen 2026-05-30 (see §9.E), formally open.\n"
             "- **Conjecture C1'** (2-WL extension, E10). The same bracket "
             "  with $\\Pi_\\mathcal{A}$ replaced by the 2-WL partition. "
             "  No proof; experimental probe still cold.\n"
             "- **Proposition 3.6** (prior-aware Fano sharpening) is paper-only "
             "  (no claim ID, no Lean witness, no decision gate) and **out of "
             "  scope** of the TMLR submission — explicit known gap.\n\n"
             "**Lean witness (BLUE, optional).** A Lean 4 mechanisation skeleton "
             "lives in `partition-sandwich-preprint/formal/` — contributing here "
             "is BLUE in the syllabus colour code (pure rigour polish, skip "
             "freely). The Python+Julia tracks of this onboarding never depend on it."),
        *_setup_cells("m5"),
        Cell("demo",
             "from onboarding.projects import reflect\n"
             "entries = list(reflect.dump(_PROJECTS / '.reflection.jsonl'))\n"
             "print(f'collected {len(entries)} reflection entries')\n"
             "from collections import Counter\n"
             "counter = Counter(r['level'] for r in entries)\n"
             "print('by level:', dict(counter))\n"),
        Cell("gate",
             "# Gate: at least 1 entry; HIGH dominates LOW for a well-calibrated learner.\n"
             "assert len(entries) >= 1, 'M5: reflection log empty — run HW1..HW4 + M1..M4 first'\n"
             "print(f'[GATE OK] M5: {len(entries)} entries logged')\n"),
        Cell("demo",
             "for r in entries[-20:]:\n"
             "    print(f\"  [{r['level']:>10}] {r['notebook']}/{r['concept']}: {r['claim']}\")\n"),
        Cell("md", "**End of M5.**"),
    ]


# --------------------------------------------------------------------------
# M6: Advanced — multi-dataset, multi-architecture sweep.
# --------------------------------------------------------------------------
def m6_cells() -> list[Cell]:
    return [
        Cell("md",
             "# Milestone 6 — Advanced: multi-dataset, multi-architecture sweep\n\n"
             "Extends M4 to Cora / Citeseer / Pubmed × {MLP, GCN, SAGE, GIN}. "
             "Optional sections cover GAT, ogbn-arxiv, MUTAG, PROTEINS (gated on availability)."),
        *_setup_cells("m6"),
        _import_shared(),

        Cell("demo",
             "import torch, torch.nn.functional as F\n"
             "from torch_geometric.datasets import Planetoid\n"
             "from torch_geometric.nn import GCNConv, SAGEConv, GINConv\n"
             "torch.manual_seed(0); np.random.seed(0)\n"
             "device = torch.device('cpu')\n"
             "_CACHE = Path.home() / '.cache' / 'planetoid'\n"
             "datasets = {}\n"
             "for name in ['Cora', 'Citeseer', 'Pubmed']:\n"
             "    try:\n"
             "        datasets[name] = Planetoid(root=str(_CACHE / name), name=name)[0].to(device)\n"
             "        print(f'  {name}: n={datasets[name].num_nodes}, m={datasets[name].num_edges}, K={int(datasets[name].y.max())+1}')\n"
             "    except Exception as e:\n"
             "        print(f'  {name}: skipped ({type(e).__name__})')\n"),

        Cell("demo",
             "def build(name, in_dim, h, k):\n"
             "    if name == 'MLP':\n"
             "        return torch.nn.Sequential(torch.nn.Linear(in_dim,h), torch.nn.ReLU(), torch.nn.Linear(h,k))\n"
             "    raise NotImplementedError\n"
             "\n"
             "class GCN(torch.nn.Module):\n"
             "    def __init__(self,d,h,k): super().__init__(); self.c1=GCNConv(d,h); self.c2=GCNConv(h,k)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "class SAGE(torch.nn.Module):\n"
             "    def __init__(self,d,h,k): super().__init__(); self.c1=SAGEConv(d,h); self.c2=SAGEConv(h,k)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "class GIN(torch.nn.Module):\n"
             "    def __init__(self,d,h,k):\n"
             "        super().__init__()\n"
             "        m1=torch.nn.Sequential(torch.nn.Linear(d,h),torch.nn.ReLU(),torch.nn.Linear(h,h))\n"
             "        m2=torch.nn.Sequential(torch.nn.Linear(h,h),torch.nn.ReLU(),torch.nn.Linear(h,k))\n"
             "        self.c1=GINConv(m1); self.c2=GINConv(m2)\n"
             "    def forward(self,x,ei): return self.c2(F.relu(self.c1(x,ei)),ei)\n"
             "\n"
             "def train(model, data, epochs=80):\n"
             "    opt = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)\n"
             "    for _ in range(epochs):\n"
             "        model.train(); opt.zero_grad()\n"
             "        try:\n"
             "            out = model(data.x, data.edge_index)\n"
             "        except TypeError:\n"
             "            out = model(data.x)\n"
             "        loss = F.cross_entropy(out[data.train_mask], data.y[data.train_mask])\n"
             "        loss.backward(); opt.step()\n"
             "    model.eval()\n"
             "    with torch.no_grad():\n"
             "        try: logits = model(data.x, data.edge_index)\n"
             "        except TypeError: logits = model(data.x)\n"
             "        p = logits.argmax(-1)\n"
             "        return float((p[data.test_mask] == data.y[data.test_mask]).float().mean())\n"
             "\n"
             "ARCHS = {'MLP': None, 'GCN': GCN, 'SAGE': SAGE, 'GIN': GIN}\n"
             "rows = []\n"
             "for ds_name, data in datasets.items():\n"
             "    K = int(data.y.max())+1\n"
             "    for a_name, a_cls in ARCHS.items():\n"
             "        torch.manual_seed(0)\n"
             "        if a_cls is None:\n"
             "            model = build('MLP', data.num_features, 64, K)\n"
             "        else:\n"
             "            model = a_cls(data.num_features, 64, K)\n"
             "        acc = train(model, data, epochs=80)\n"
             "        rows.append((ds_name, a_name, acc))\n"
             "        print(f'  {ds_name:>9}/{a_name:>5}: acc={acc:.3f}')\n"),

        Cell("gate",
             "# Gate: at least one structural arch beats MLP on at least one dataset.\n"
             "best_struct = max(acc for ds, a, acc in rows if a != 'MLP')\n"
             "best_mlp    = max((acc for ds, a, acc in rows if a == 'MLP'), default=0.0)\n"
             "assert best_struct > best_mlp - 0.02, f'M6: structural arches never beat MLP'\n"
             "print(f'[GATE OK] M6: best structural={best_struct:.3f}, best MLP={best_mlp:.3f}')\n"),

        Cell("demo",
             "import pandas as pd\n"
             "df = pd.DataFrame(rows, columns=['dataset','arch','test_acc'])\n"
             "pivot = df.pivot(index='arch', columns='dataset', values='test_acc')\n"
             "print(pivot)\n"
             "fig, ax = plt.subplots(figsize=(6,3.5))\n"
             "pivot.plot(kind='bar', ax=ax); ax.set_ylabel('test acc'); ax.set_title('M6 — arch × dataset sweep')\n"
             "_plots = _PROJECTS / 'capstone' / 'milestone6' / 'plots'; _plots.mkdir(parents=True, exist_ok=True)\n"
             "plt.tight_layout(); fig.savefig(_plots / 'm6_sweep.png', dpi=120); plt.show()\n"),
        Cell("reflect",
             "reflect.log('M6.advanced_sweep', f'{len(rows)} (dataset, arch) cells trained; best structural={best_struct:.3f}', 'HIGH')\n"),

        Cell("md", "### Optional — heavier sweeps via Modal\nUncomment to launch on T4."),
        Cell("demo",
             "# from onboarding.projects import modal_app\n"
             "# if modal_app._MODAL_OK and modal_app.app is not None:\n"
             "#     with modal_app.app.run():\n"
             "#         print(modal_app.nas_sweep.remote(epochs=200))\n"
             "print('[stub] Modal optional sweep — see M3/M4 for the live version.')\n"),
        Cell("md", "**End of M6.**"),
    ]


def _write(cells, target: Path):
    target.parent.mkdir(parents=True, exist_ok=True)
    nb = build_notebook(cells, solution=True)
    with target.open("w") as f:
        nbf.write(nb, f)
    print(f"wrote {target}")


def main() -> None:
    capstone = Path(__file__).resolve().parent.parent / "capstone"
    _write(m1_cells(), capstone / "milestone1" / "m1.ipynb")
    _write(m2_cells(), capstone / "milestone2" / "m2.ipynb")
    _write(m3_cells(), capstone / "milestone3" / "m3.ipynb")
    _write(m4_cells(), capstone / "milestone4" / "m4.ipynb")
    _write(m5_cells(), capstone / "milestone5" / "m5.ipynb")
    _write(m6_cells(), capstone / "milestone6" / "m6_advanced.ipynb")


if __name__ == "__main__":
    main()
